services:
  backend:
    build: ./backend
    container_name: proshop-backend
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/proshop
      - JWT_SECRET=abc123
      - PAYPAL_CLIENT_ID=your_paypal_client_id
    depends_on:
      - mongo
    networks:
      - proshop-network

  frontend:
    build: ./frontend
    container_name: proshop-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - proshop-network

  mongo:
    image: mongo:4.4
    container_name: proshop-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: proshop
    networks:
      - proshop-network

networks:
  proshop-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local