version: '3.8'

services:
  backend:
    build: ./backend
    container_name: proshop-backend
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    networks:
      - proshop-network

  frontend:
    build: ./frontend
    container_name: proshop-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - proshop-network

  mongo:
    image: mongo:4.4
    container_name: proshop-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - proshop-network

networks:
  proshop-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local