global:
  scrape_interval: 15s #Scrape interval to every 15 seconds.
  evaluation_interval: 15s #Evaluate rules every 15 seconds.
  
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          instance_name: "Prometheus Server"

  - job_name: "grafana"
    static_configs:
      - targets: ["localhost:4000"]
        labels:
          instance_name: "Grafana Server"

  - job_name: 'mongo'
    static_configs:
      - targets: ['mongo:27017']
        labels:
          instance_name: "MongoDB Metrics"
